INSERT INTO <?php echo $wpdb->prefix; ?>cities ( city_name, state_code, state_name, country_code, country ) VALUES ("<?php esc_html_e('Diekirch', 'acfcs' ); ?>", "na", "n/a", "LU", "<?php esc_html_e( 'Luxembourg', 'acfcs' ); ?>");
INSERT INTO <?php echo $wpdb->prefix; ?>cities ( city_name, state_code, state_name, country_code, country ) VALUES ("<?php esc_html_e('Differdange', 'acfcs' ); ?>", "n/a", "LU", "<?php esc_html_e( 'Luxembourg', 'acfcs' ); ?>");
INSERT INTO <?php echo $wpdb->prefix; ?>cities ( city_name, state_code, state_name, country_code, country ) VALUES ("<?php esc_html_e('Dudelange', 'acfcs' ); ?>", "na", "n/a", "LU", "<?php esc_html_e( 'Luxembourg', 'acfcs' ); ?>");
INSERT INTO <?php echo $wpdb->prefix; ?>cities ( city_name, state_code, state_name, country_code, country ) VALUES ("<?php esc_html_e('Echternach', 'acfcs' ); ?>", "n/a", "LU", "<?php esc_html_e( 'Luxembourg', 'acfcs' ); ?>");
INSERT INTO <?php echo $wpdb->prefix; ?>cities ( city_name, state_code, state_name, country_code, country ) VALUES ("<?php esc_html_e('Esch-sur-Alzette', 'acfcs' ); ?>", "na", "n/a", "LU", "<?php esc_html_e( 'Luxembourg', 'acfcs' ); ?>");
INSERT INTO <?php echo $wpdb->prefix; ?>cities ( city_name, state_code, state_name, country_code, country ) VALUES ("<?php esc_html_e('Ettelbruck', 'acfcs' ); ?>", "n/a", "LU", "<?php esc_html_e( 'Luxembourg', 'acfcs' ); ?>");
INSERT INTO <?php echo $wpdb->prefix; ?>cities ( city_name, state_code, state_name, country_code, country ) VALUES ("<?php esc_html_e('Grevenmacher', 'acfcs' ); ?>", "na", "n/a", "LU", "<?php esc_html_e( 'Luxembourg', 'acfcs' ); ?>");
INSERT INTO <?php echo $wpdb->prefix; ?>cities ( city_name, state_code, state_name, country_code, country ) VALUES ("<?php esc_html_e('Luxembourg City', 'acfcs' ); ?>", "n/a", "LU", "<?php esc_html_e( 'Luxembourg', 'acfcs' ); ?>");
INSERT INTO <?php echo $wpdb->prefix; ?>cities ( city_name, state_code, state_name, country_code, country ) VALUES ("<?php esc_html_e('Remich', 'acfcs' ); ?>", "na", "n/a", "LU", "<?php esc_html_e( 'Luxembourg', 'acfcs' ); ?>");
INSERT INTO <?php echo $wpdb->prefix; ?>cities ( city_name, state_code, state_name, country_code, country ) VALUES ("<?php esc_html_e('Rumelange', 'acfcs' ); ?>", "n/a", "LU", "<?php esc_html_e( 'Luxembourg', 'acfcs' ); ?>");
INSERT INTO <?php echo $wpdb->prefix; ?>cities ( city_name, state_code, state_name, country_code, country ) VALUES ("<?php esc_html_e('Vianden', 'acfcs' ); ?>", "na", "n/a", "LU", "<?php esc_html_e( 'Luxembourg', 'acfcs' ); ?>");
INSERT INTO <?php echo $wpdb->prefix; ?>cities ( city_name, state_code, state_name, country_code, country ) VALUES ("<?php esc_html_e('Wiltz', 'acfcs' ); ?>", "n/a", "LU", "<?php esc_html_e( 'Luxembourg', 'acfcs' ); ?>");

<?php $this->acfcs_errors()->add( 'success_cities_imported_luxembourg', esc_html__( 'Successfully imported 12 cities for Luxembourg.', 'acf-city-selector' ) ); ?>
